import { useEffect, useRef, useState } from "react";
import { api } from "../api";

// Keyword weights used to be hand-edited here. They're now generated by
// Claude from these structured fields (see keyword_gen.py) whenever one of
// them changes -- this form only collects who the reader is, never a
// weight number.
function SavingTimer() {
  const [seconds, setSeconds] = useState(0);
  useEffect(() => {
    const id = setInterval(() => setSeconds((s) => s + 1), 1000);
    return () => clearInterval(id);
  }, []);
  return <span>{seconds}s</span>;
}

function Chip({ text, onRemove }) {
  return (
    <span className="chip">
      {text}
      <button type="button" className="chip-remove" onClick={onRemove} aria-label={`Remove ${text}`}>
        &times;
      </button>
    </span>
  );
}

function ChipInput({ items, onAdd, onRemove, placeholder }) {
  const [text, setText] = useState("");

  function submit(e) {
    e.preventDefault();
    const value = text.trim();
    if (!value || items.includes(value)) return;
    onAdd(value);
    setText("");
  }

  return (
    <div>
      <div className="chip-list">
        {items.map((item) => (
          <Chip key={item} text={item} onRemove={() => onRemove(item)} />
        ))}
      </div>
      <form className="chip-add-form" onSubmit={submit}>
        <input type="text" placeholder={placeholder} value={text} onChange={(e) => setText(e.target.value)} />
        <button type="submit">Add</button>
      </form>
    </div>
  );
}

export default function ProfileEditor({ profiles, selectedProfileId, onSaved }) {
  const selected = profiles.find((p) => p.id === selectedProfileId);
  const [draft, setDraft] = useState(null);
  const [saveState, setSaveState] = useState(null); // null | "saving" | "saved" | "error"
  const [saveError, setSaveError] = useState(null);
  const [savedKeywordCount, setSavedKeywordCount] = useState(null);
  const clearSavedTimeout = useRef(null);

  // Load a fresh editable copy whenever the selected profile changes --
  // deliberately NOT re-synced on every `profiles` change, so mid-edit
  // state survives unrelated re-renders (e.g. a background refetch).
  useEffect(() => {
    if (selected) {
      setDraft(JSON.parse(JSON.stringify(selected)));
      setSaveState(null);
      setSaveError(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedProfileId]);

  useEffect(() => () => clearTimeout(clearSavedTimeout.current), []);

  if (!selected || !draft) {
    return <p className="muted">No profile selected.</p>;
  }

  function updateField(field, value) {
    setDraft((d) => ({ ...d, [field]: value }));
  }

  function updateSection(index, value) {
    setDraft((d) => {
      const next = [...d.sections];
      next[index] = value;
      return { ...d, sections: next };
    });
  }

  function removeSection(index) {
    setDraft((d) => ({ ...d, sections: d.sections.filter((_, i) => i !== index) }));
  }

  function addSection() {
    setDraft((d) => ({ ...d, sections: [...d.sections, ""] }));
  }

  function addTopicToAvoid(topic) {
    setDraft((d) => ({ ...d, topics_to_avoid: [...(d.topics_to_avoid ?? []), topic] }));
  }

  function removeTopicToAvoid(topic) {
    setDraft((d) => ({ ...d, topics_to_avoid: d.topics_to_avoid.filter((t) => t !== topic) }));
  }

  function updateFeed(index, field, value) {
    setDraft((d) => {
      const next = d.feeds.map((f, i) => (i === index ? { ...f, [field]: value } : f));
      return { ...d, feeds: next };
    });
  }

  function removeFeed(index) {
    setDraft((d) => ({ ...d, feeds: d.feeds.filter((_, i) => i !== index) }));
  }

  function addFeed() {
    setDraft((d) => ({ ...d, feeds: [...d.feeds, { name: "", url: "", category: "" }] }));
  }

  async function handleSave() {
    setSaveState("saving");
    setSaveError(null);
    clearTimeout(clearSavedTimeout.current);
    try {
      const updated = await api.updateProfile(draft.id, draft);
      setSaveState("saved");
      setSavedKeywordCount(Object.keys(updated.keywords ?? {}).length);
      onSaved(updated);
      clearSavedTimeout.current = setTimeout(() => setSaveState((s) => (s === "saved" ? null : s)), 4000);
    } catch (err) {
      setSaveState("error");
      setSaveError(err.message);
    }
  }

  return (
    <div className="profile-editor">
      <section className="editor-block">
        <h2>About you</h2>
        <div className="field-grid">
          <label>
            Name
            <input type="text" value={draft.name} onChange={(e) => updateField("name", e.target.value)} />
          </label>
          <label>
            Age
            <input
              type="number"
              value={draft.age ?? ""}
              onChange={(e) => updateField("age", e.target.value === "" ? null : Number(e.target.value))}
            />
          </label>
          <label>
            Industry
            <input type="text" value={draft.industry ?? ""} onChange={(e) => updateField("industry", e.target.value)} />
          </label>
          <label>
            Position
            <input type="text" value={draft.position ?? ""} onChange={(e) => updateField("position", e.target.value)} />
          </label>
          <label>
            Company
            <input type="text" value={draft.company ?? ""} onChange={(e) => updateField("company", e.target.value)} />
          </label>
          <label>
            Recipient email
            <input type="email" value={draft.recipient_email} onChange={(e) => updateField("recipient_email", e.target.value)} />
          </label>
        </div>
        <label className="field-block">
          Anything else worth knowing? <span className="muted">(optional)</span>
          <textarea
            rows={4}
            placeholder="What you already read, what's redundant to you, specific peers or lanes to cover densely..."
            value={draft.about ?? ""}
            onChange={(e) => updateField("about", e.target.value)}
          />
        </label>
      </section>

      <section className="editor-block">
        <h2>Sections</h2>
        <p className="muted">Used to bucket selected stories in the digest.</p>
        {draft.sections.map((section, i) => (
          <div className="row-inline" key={i}>
            <input type="text" value={section} onChange={(e) => updateSection(i, e.target.value)} />
            <button type="button" className="btn-remove" onClick={() => removeSection(i)}>
              &times;
            </button>
          </div>
        ))}
        <button type="button" className="btn-secondary" onClick={addSection}>
          + Add section
        </button>
      </section>

      <section className="editor-block">
        <h2>Topics to avoid</h2>
        <p className="muted">
          Actively suppressed even if they'd otherwise seem relevant -- e.g. "celebrity news", "sports".
        </p>
        <ChipInput
          items={draft.topics_to_avoid ?? []}
          onAdd={addTopicToAvoid}
          onRemove={removeTopicToAvoid}
          placeholder="topic to avoid"
        />
      </section>

      <section className="editor-block">
        <div className="editor-block-header">
          <h2>Feeds</h2>
          <span className="count-badge">{draft.feeds.length}</span>
        </div>
        {draft.feeds.map((feed, i) => (
          <div className="feed-row" key={i}>
            <input
              type="text"
              placeholder="display name"
              value={feed.name}
              onChange={(e) => updateFeed(i, "name", e.target.value)}
            />
            <input
              type="text"
              placeholder="feed URL"
              value={feed.url}
              onChange={(e) => updateFeed(i, "url", e.target.value)}
            />
            <button type="button" className="btn-remove" onClick={() => removeFeed(i)}>
              &times;
            </button>
          </div>
        ))}
        <button type="button" className="btn-secondary" onClick={addFeed}>
          + Add feed
        </button>
      </section>

      <div className="save-bar">
        <button type="button" className="btn-primary" onClick={handleSave} disabled={saveState === "saving"}>
          {saveState === "saving" ? "Saving…" : "Save"}
        </button>
        {saveState === "saving" && (
          <span className="loading-indicator">
            Updating your keyword profile -- usually 10-20s (<SavingTimer />)
          </span>
        )}
        {saveState === "saved" && (
          <span className="save-status ok">Saved -- {savedKeywordCount} keywords generated</span>
        )}
        {saveState === "error" && <span className="save-status error">Failed to save: {saveError}</span>}
      </div>
    </div>
  );
}
